import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored shadcn registry component. This file is generated by
    // `npx shadcn@latest add @mapcn/map` and is overwritten on every re-add,
    // so linting it only produces churn we cannot fix upstream.
    "src/components/ui/map.tsx",
    // Static assets, including the maplibre-gl worker copied in on postinstall.
    "public/**",
  ]),
]);

export default eslintConfig;
